print ("input")
Nama = input("Nama\t\t\t:")
NIM = input("NIM\t\t\t:")
KelasParalel = input("Kelas Paralel\t\t:")
Ttl = input("Tempat/Tanggal Lahir\t:")
Alamat = input("Alamat\t\t\t:")
Hobby = input("Hobby\t\t\t:")
NoHP = input("No.Hp\t\t\t:")
print("output")
print("Nama\t\t\t:", Nama)
print("NIM\t\t\t:", NIM)
print("Kelas Paralel\t\t:", KelasParalel)
print("Tempat/Tanggal Lahir\t:", Ttl)
print("Alamat\t\t\t:", Alamat)
print("Hobby\t\t\t:", Hobby)
print("No.Hp\t\t\t:", NoHP)